@startuml

'
' One Dark theme contrast
'

'
' Colors
'
' Foreground
!$color_bg       = "#1a1c1f"
!$color_bg_light = "#2a2d31"

' Background
!$color_fg       = "#e6e6e6"

!$color_red      = "#ff5c67"
!$color_green    = "#7edc75"
!$color_yellow   = "#ffd166"
!$color_blue     = "#5ab0f6"
!$color_purple   = "#c792ea"
!$color_teal     = "#4dd0e1"

!$color_primary  = $color_blue
' ...FontColor Properties (DefaultFontColor disabled)
!$color_font     = $color_fg              

skinparam backgroundColor   $color_bg

skinparam class {
  ' Keep dark Circle font color at header
  AttributeFontColor        $color_fg     
}

skinparam {
  '
  ' Activity
  '
  ActivityBackgroundColor        $color_bg_light
  ActivityBarColor               $color_fg
  ActivityBorderColor            $color_primary
  ' ActivityBorderThickness
  ActivityDiamondBackgroundColor $color_bg_light
  ActivityDiamondBorderColor     $color_primary
  ' ActivityDiamondFontColor
  ' ActivityDiamondFontName
  ' ActivityDiamondFontSize
  ' ActivityDiamondFontStyle
  ActivityEndColor               $color_red
  ' ActivityFontColor
  ' ActivityFontName
  ' ActivityFontSize
  ' ActivityFontStyle
  ActivityStartColor             $color_green
  ActivityStopColor              $color_red

  '
  ' Actor
  '
  ActorBackgroundColor        $color_bg_light
  ActorBorderColor            $color_primary
  ' ActorFontColor
  ' ActorFontName
  ' ActorFontSize
  ' ActorFontStyle
  ActorStereotypeFontColor    $color_fg
  ' ActorStereotypeFontName
  ' ActorStereotypeFontSize
  ' ActorStereotypeFontStyle

  '
  ' Agent
  '
  AgentBackgroundColor       $color_bg_light
  AgentBorderColor           $color_primary
  ' AgentBorderThickness
  AgentFontColor          $color_font
  ' AgentFontName
  ' AgentFontSize
  ' AgentFontStyle
  AgentStereotypeFontColor          $color_font
  ' AgentStereotypeFontName
  ' AgentStereotypeFontSize
  ' AgentStereotypeFontStyle

  '
  ' Archimate
  '
  ' ArchimateBackgroundColor
  '
  ' ArchimateBorderColor
  '
  ' ArchimateBorderThickness 
  ArchimateFontColor          $color_font
  '
  ' ArchimateFontName
  ' ArchimateFontSize
  '
  ' ArchimateFontStyle
  '
  ArchimateStereotypeFontColor          $color_font
  ' ArchimateStereotypeFontName
  '
  ' ArchimateStereotypeFontSize
  ' ArchimateStereotypeFontStyle
  
  '
  ' Arrow
  '
  ArrowColor $color_primary
  ArrowFontColor          $color_font
  ' ArrowFontName
  ' ArrowFontSize
  ' ArrowFontStyle
  ' ArrowHeadColor
  ' ArrowLollipopColor
  ' ArrowMessageAlignment
  ' ArrowThickness

  '
  ' Artifact
  '
  ArtifactBackgroundColor     $color_bg_light
  ArtifactBorderColor         $color_primary
  ArtifactFontColor           $color_font
  ' ArtifactFontName
  ' ArtifactFontSize
  ' ArtifactFontStyle
  ArtifactStereotypeFontColor           $color_font
  ' ArtifactStereotypeFontName
  ' ArtifactStereotypeFontSize
  ' ArtifactStereotypeFontStyle

  '
  ' Background color
  '
  BackgroundColor $color_bg
  
  ' 
  ' Biddable (?)
  '
  ' BiddableBackgroundColor
  ' BiddableBorderColor

  '
  ' Boundary
  '
  BoundaryBackgroundColor     $color_bg_light
  BoundaryBorderColor         $color_primary
  BoundaryFontColor           $color_font
  ' BoundaryFontName
  ' BoundaryFontSize
  ' BoundaryFontStyle
  BoundaryStereotypeFontColor $color_fg
  ' BoundaryStereotypeFontName
  ' BoundaryStereotypeFontSize
  ' BoundaryStereotypeFontStyle

  '
  ' Box padding
  '
  ' BoxPadding
  
  '
  ' Caption
  '
  CaptionFontColor $color_fg
  ' CaptionFontName
  ' CaptionFontSize
  ' CaptionFontStyle

  '
  ' Card
  '
  CardBackgroundColor     $color_bg_light
  CardBorderColor         $color_primary
  ' CardBorderThickness
  CardFontColor $color_font
  ' CardFontName
  ' CardFontSize
  ' CardFontStyle
  CardStereotypeFontColor $color_font
  ' CardStereotypeFontName
  ' CardStereotypeFontSize
  ' CardStereotypeFontStyle
  
  '
  ' Circled character (in class header)
  '
  CircledCharacterFontColor $color_font
  ' CircledCharacterFontName
  ' CircledCharacterFontSize
  ' CircledCharacterFontStyle
  ' CircledCharacterRadius

  '
  ' Class attribute
  '
  ClassAttributeFontColor $color_font
  ' ClassAttributeFontName
  ' ClassAttributeFontSize
  ' ClassAttributeFontStyle
  ' ClassAttributeIconSize

  '
  ' Class
  '
  ClassBackgroundColor   $color_bg_light
  ClassBorderColor       $color_fg
  ' ClassBorderThickness
  ClassFontColor $color_font
  ' ClassFontName
  ' ClassFontSize
  ' ClassFontStyle
  
  '
  ' Class header
  '
  ' ClassHeaderBackgroundColor

  '
  ' Class stereotype
  '
  ClassStereotypeFontColor $color_font
  ' ClassStereotypeFontName
  ' ClassStereotypeFontSize
  ' ClassStereotypeFontStyle

  '
  ' Cloud
  '
  CloudBackgroundColor        $color_bg_light
  CloudBorderColor            $color_primary
  CloudFontColor $color_font
  ' CloudFontName
  ' CloudFontSize
  ' CloudFontStyle
  CloudStereotypeFontColor $color_font
  ' CloudStereotypeFontName
  ' CloudStereotypeFontSize
  ' CloudStereotypeFontStyle
  
  '
  ' Collections
  '
  CollectionsBackgroundColor $color_bg_light
  CollectionsBorderColor     $color_primary

  ' TODO
  ' ColorArrowSeparationSpace
  
  '
  ' Component
  '
  ComponentBackgroundColor       $color_bg_light
  ComponentBorderColor           $color_primary
  ' ComponentBorderThickness
  ComponentFontColor $color_font
  ' ComponentFontName
  ' ComponentFontSize
  ' ComponentFontStyle
  ComponentStereotypeFontColor $color_font
  ' ComponentStereotypeFontName
  ' ComponentStereotypeFontSize
  ' ComponentStereotypeFontStyle

  ' ComponentStyle

  '
  ' Condition styles
  '
  ' ConditionEndStyle
  ' ConditionStyle

  '
  ' Control
  '
  ControlBackgroundColor $color_bg_light
  ControlBorderColor     $color_primary
  ControlFontColor       $color_fg
  ' ControlFontName
  ' ControlFontSize
  ' ControlFontStyle
  ControlStereotypeFontColor $color_fg
  ' ControlStereotypeFontName
  ' ControlStereotypeFontSize
  ' ControlStereotypeFontStyle

  '
  ' Database
  '
  DatabaseBackgroundColor       $color_bg_light
  DatabaseBorderColor           $color_primary
  DatabaseFontColor             $color_font
  ' DatabaseFontName
  ' DatabaseFontSize
  ' DatabaseFontStyle
  DatabaseStereotypeFontColor   $color_font
  ' DatabaseStereotypeFontName
  ' DatabaseStereotypeFontSize
  ' DatabaseStereotypeFontStyle

  '
  ' Default font styles
  '
  ' DefaultFontColor $color_fg
  ' https://github.com/twbs/bootstrap/blob/v4.5.3/scss/_variables.scss#L277
  DefaultFontName -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"
  ' DefaultFontSize
  ' DefaultFontStyle

  ' TODO: get this to work
  ' https://github.com/twbs/bootstrap/blob/v4.5.3/scss/_variables.scss#L278
  ' DefaultMonospacedFontName SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace

  ' DefaultTextAlignment
  

  '
  ' Designed (?)
  '
  ' DesignedBackgroundColor
  ' DesignedBorderColor
  ' DesignedDomainBorderThickness
  DesignedDomainFontColor   $color_font
  ' DesignedDomainFontName
  ' DesignedDomainFontSize
  ' DesignedDomainFontStyle
  DesignedDomainStereotypeFontColor   $color_font
  ' DesignedDomainStereotypeFontName
  ' DesignedDomainStereotypeFontSize
  ' DesignedDomainStereotypeFontStyle

  '
  ' Diagram border
  '
  ' DiagramBorderColor
  ' DiagramBorderThickness
  
  '
  ' Domain (?)
  '
  ' DomainBackgroundColor
  ' DomainBorderColor
  ' DomainBorderThickness
  DomainFontColor   $color_font
  ' DomainFontName
  ' DomainFontSize
  ' DomainFontStyle
  DomainStereotypeFontColor   $color_font
  ' DomainStereotypeFontName
  ' DomainStereotypeFontSize
  ' DomainStereotypeFontStyle

  ' Dpi

  '
  ' Entity
  '
  EntityBackgroundColor $color_bg_light
  EntityBorderColor     $color_primary
  EntityFontColor   $color_font
  ' EntityFontName
  ' EntityFontSize
  ' EntityFontStyle
  EntityStereotypeFontColor   $color_font
  
  '
  ' Entity stereotype
  '
  ' EntityStereotypeFontName
  ' EntityStereotypeFontSize
  ' EntityStereotypeFontStyle
  '
  ' EnumBackgroundColor

  '
  ' File
  '
  FileBackgroundColor $color_bg_light
  FileBorderColor     $color_primary
  FileFontColor   $color_font
  ' FileFontName
  ' FileFontSize
  ' FileFontStyle

  '
  ' File stereotype
  '
  FileStereotypeFontColor   $color_font
  ' FileStereotypeFontName
  ' FileStereotypeFontSize
  ' FileStereotypeFontStyle

  ' FixCircleLabelOverlapping
 
  '
  ' Folder
  '
  FolderBackgroundColor $color_bg_light
  FolderBorderColor     $color_primary
  FolderFontColor   $color_font
  ' FolderFontName
  ' FolderFontSize
  ' FolderFontStyle
  
  '
  ' Folder stereotype
  '
  FolderStereotypeFontColor   $color_font
  ' FolderStereotypeFontName
  ' FolderStereotypeFontSize
  ' FolderStereotypeFontStyle
  '
  FooterFontColor   $color_font
  '
  ' FooterFontName
  ' FooterFontSize
  '
  ' FooterFontStyle

  '
  ' Frame
  '
  FrameBackgroundColor       $color_bg_light
  FrameBorderColor           $color_primary
  FrameFontColor    $color_font
  ' FrameFontName
  ' FrameFontSize
  ' FrameFontStyle
  FrameStereotypeFontColor    $color_font
  ' FrameStereotypeFontName
  ' FrameStereotypeFontSize
  ' FrameStereotypeFontStyle

  '
  ' Hexagon
  '
  HexagonBackgroundColor $color_bg_light
  HexagonBorderColor     $color_primary

  ' GenericDisplay
  ' Guillemet
  '
  ' Handwritten
  HeaderFontColor   $color_font
  '
  ' HeaderFontName
  ' HeaderFontSize
  '
  ' HeaderFontStyle
  '
  ' HyperlinkColor
  ' HyperlinkUnderline
  '
  ' IconIEMandatoryColor
  ' IconPackageBackgroundColor
  '
  ' IconPackageColor
  '
  ' IconPrivateBackgroundColor
  ' IconPrivateColor
  '
  ' IconProtectedBackgroundColor
  ' IconProtectedColor
  '
  ' IconPublicBackgroundColor
  '
  ' IconPublicColor

  '
  ' Interface
  '
  InterfaceBackgroundColor       $color_bg_light
  InterfaceBorderColor           $color_primary
  InterfaceFontColor    $color_font
  ' InterfaceFontName
  ' InterfaceFontSize
  ' InterfaceFontStyle
  InterfaceStereotypeFontColor    $color_font
  ' InterfaceStereotypeFontName
  ' InterfaceStereotypeFontSize
  ' InterfaceStereotypeFontStyle

  '
  ' Legend
  '
  LegendBackgroundColor   $color_bg_light
  LegendBorderColor       $color_fg
  ' LegendBorderThickness
  LegendFontColor   $color_font
  ' LegendFontName
  ' LegendFontSize
  ' LegendFontStyle

  ' LexicalBackgroundColor
  '
  ' LexicalBorderColor
  '
  ' LifelineStrategy
  ' Linetype
  '
  ' MachineBackgroundColor
  ' MachineBorderColor
  '
  ' MachineBorderThickness
  '
  MachineFontColor    $color_font
  ' MachineFontName
  '
  ' MachineFontSize
  ' MachineFontStyle
  '
  MachineStereotypeFontColor    $color_font
  '
  ' MachineStereotypeFontName
  ' MachineStereotypeFontSize
  '
  ' MachineStereotypeFontStyle
  ' MaxAsciiMessageLength
  '
  ' MaxMessageSize
  '
  ' MinClassWidth
  ' Monochrome
  
  '
  ' Node
  '
  NodeBackgroundColor       $color_bg_light
  NodeBorderColor           $color_primary
  NodeFontColor   $color_font
  ' NodeFontName
  ' NodeFontSize
  ' NodeFontStyle
  NodeStereotypeFontColor   $color_font
  ' NodeStereotypeFontName
  ' NodeStereotypeFontSize
  ' NodeStereotypeFontStyle
  
  ' Nodesep

  '
  ' Note
  '
  NoteBackgroundColor   $color_yellow
  NoteBorderColor       $color_bg
  ' NoteBorderThickness
  NoteFontColor         $color_bg
  ' NoteFontName
  ' NoteFontSize
  ' NoteFontStyle
  ' NoteShadowing
  ' NoteTextAlignment
  
  '
  ' Object
  '
  ObjectAttributeFontColor    $color_font
  ' ObjectAttributeFontName
  ' ObjectAttributeFontSize
  ' ObjectAttributeFontStyle
  ObjectBackgroundColor       $color_bg_light
  ObjectBorderColor           $color_primary
  ' ObjectBorderThickness
  ObjectFontColor     $color_font
  ' ObjectFontName
  ' ObjectFontSize
  ' ObjectFontStyle
  ObjectStereotypeFontColor     $color_font
  ' ObjectStereotypeFontName
  ' ObjectStereotypeFontSize
  ' ObjectStereotypeFontStyle
  
  '
  ' Package
  '
  PackageBackgroundColor       $color_bg
  PackageBorderColor           $color_primary
  ' PackageBorderThickness
  PackageFontColor             $color_fg
  ' PackageFontName
  ' PackageFontSize
  ' PackageFontStyle
  PackageStereotypeFontColor    $color_font
  ' PackageStereotypeFontName
  ' PackageStereotypeFontSize
  ' PackageStereotypeFontStyle

  ' PackageStyle
  '
  ' PackageTitleAlignment
  '
  ' Padding
  ' PageBorderColor
  '
  ' PageExternalColor
  ' PageMargin
  
  '
  ' Participant
  '
  ParticipantBackgroundColor $color_bg_light
  ParticipantBorderColor     $color_primary
  ParticipantFontColor    $color_font
  ' ParticipantFontName
  ' ParticipantFontSize
  ' ParticipantFontStyle
  ' ParticipantPadding
  ParticipantStereotypeFontColor    $color_font
  ' ParticipantStereotypeFontName
  ' ParticipantStereotypeFontSize
  ' ParticipantStereotypeFontStyle
  
  '
  ' Partition
  '
  PartitionBackgroundColor transparent
  PartitionBorderColor     $color_fg
  ' PartitionBorderThickness
  PartitionFontColor    $color_font
  ' PartitionFontName
  ' PartitionFontSize
  ' PartitionFontStyle
  
  ' PathHoverColor

  '
  ' Person
  '
  PersonBackgroundColor $color_bg_light
  PersonBorderColor     $color_primary
  
  '
  ' Queue
  '
  QueueBackgroundColor       $color_bg_light
  QueueBorderColor           $color_primary
  ' QueueBorderThickness
  QueueFontColor    $color_font
  ' QueueFontName
  ' QueueFontSize
  ' QueueFontStyle
  QueueStereotypeFontColor    $color_font
  ' QueueStereotypeFontName
  ' QueueStereotypeFontSize
  ' QueueStereotypeFontStyle
  
  ' Ranksep
  
  '
  ' Rectangle
  '
  RectangleBackgroundColor       $color_bg_light
  RectangleBorderColor           $color_primary
  ' RectangleBorderThickness
  RectangleFontColor    $color_font
  ' RectangleFontName
  ' RectangleFontSize
  ' RectangleFontStyle
  RectangleStereotypeFontColor    $color_font
  ' RectangleStereotypeFontName
  ' RectangleStereotypeFontSize
  ' RectangleStereotypeFontStyle

  ' RequirementBackgroundColor
  '
  ' RequirementBorderColor
  ' RequirementBorderThickness
  '
  RequirementFontColor    $color_font
  '
  ' RequirementFontName
  ' RequirementFontSize
  '
  ' RequirementFontStyle
  RequirementStereotypeFontColor    $color_font
  '
  ' RequirementStereotypeFontName
  '
  ' RequirementStereotypeFontSize
  ' RequirementStereotypeFontStyle
  '
  ' ResponseMessageBelowArrow

  ' RoundCorner

  ' SameClassWidth
  '
  ' SequenceActorBorderThickness
  ' SequenceArrowThickness
  
  '
  ' Sequence box
  '
  SequenceBoxBackgroundColor $color_bg_light
  SequenceBoxBorderColor     $color_primary
  SequenceBoxFontColor    $color_font
  ' SequenceBoxFontName
  ' SequenceBoxFontSize
  ' SequenceBoxFontStyle

  '
  ' Sequence delay
  '
  SequenceDelayFontColor    $color_font
  ' SequenceDelayFontName
  ' SequenceDelayFontSize
  ' SequenceDelayFontStyle

  '
  ' Sequence divider
  '
  SequenceDividerBackgroundColor   $color_bg_light
  SequenceDividerBorderColor       $color_fg
  ' SequenceDividerBorderThickness
  SequenceDividerFontColor    $color_font
  ' SequenceDividerFontName
  ' SequenceDividerFontSize
  ' SequenceDividerFontStyle
  
  '
  ' Sequence group
  '
  SequenceGroupBackgroundColor       $color_bg_light
  ' SequenceGroupBodyBackgroundColor
  SequenceGroupBorderColor           $color_fg
  ' SequenceGroupBorderThickness
  SequenceGroupFontColor    $color_font
  ' SequenceGroupFontName
  ' SequenceGroupFontSize
  ' SequenceGroupFontStyle
  SequenceGroupHeaderFontColor    $color_font
  ' SequenceGroupHeaderFontName
  ' SequenceGroupHeaderFontSize
  ' SequenceGroupHeaderFontStyle

  '
  ' Sequence lifeline
  '
  SequenceLifeLineBackgroundColor   $color_bg
  SequenceLifeLineBorderColor       $color_primary
  ' SequenceLifeLineBorderThickness

  '
  ' Sequence message
  '
  ' SequenceMessageAlignment
  ' SequenceMessageTextAlignment
  SequenceNewpageSeparatorColor  $color_fg
  
  '
  ' Sequence participant
  '
  ' SequenceParticipant
  ' SequenceParticipantBorderThickness
  
  '
  ' Sequence reference
  '
  ' SequenceReferenceAlignment
  SequenceReferenceBackgroundColor        transparent
  SequenceReferenceBorderColor            $color_fg
  ' SequenceReferenceBorderThickness
  SequenceReferenceFontColor    $color_font
  ' SequenceReferenceFontName
  ' SequenceReferenceFontSize
  ' SequenceReferenceFontStyle
  SequenceReferenceHeaderBackgroundColor $color_bg_light

  '
  ' Sequence stereotype
  '
  SequenceStereotypeFontColor   $color_font
  ' SequenceStereotypeFontName
  ' SequenceStereotypeFontSize
  ' SequenceStereotypeFontStyle
  
  '
  ' Shadowing
  '
  Shadowing false

  '
  ' Stack
  '
  StackBackgroundColor       $color_bg_light
  StackBorderColor           $color_primary
  StackFontColor    $color_font
  ' StackFontName
  ' StackFontSize
  ' StackFontStyle
  StackStereotypeFontColor    $color_font
  ' StackStereotypeFontName
  ' StackStereotypeFontSize
  ' StackStereotypeFontStyle

  StateAttributeFontColor   $color_font
  ' StateAttributeFontName
  '
  ' StateAttributeFontSize
  ' StateAttributeFontStyle
  
  '
  ' State
  '
  StateBackgroundColor    $color_bg_light
  StateBorderColor        $color_primary
  StateEndColor           $color_red
  StateFontColor    $color_font
  ' StateFontName
  ' StateFontSize
  ' StateFontStyle
  ' StateMessageAlignment
  StateStartColor         $color_green

  '
  ' Stereotype
  '
  ' StereotypeABackgroundColor
  ' StereotypeABorderColor
  ' StereotypeCBackgroundColor
  ' StereotypeCBorderColor
  ' StereotypeEBackgroundColor
  ' StereotypeEBorderColor
  ' StereotypeIBackgroundColor
  ' StereotypeIBorderColor
  ' StereotypeNBackgroundColor
  ' StereotypeNBorderColor
  ' StereotypePosition
  
  '
  ' Storage
  '
  StorageBackgroundColor $color_bg_light
  StorageBorderColor     $color_fg
  StorageFontColor    $color_font
  ' StorageFontName
  ' StorageFontSize
  ' StorageFontStyle
  StorageStereotypeFontColor    $color_font
  ' StorageStereotypeFontName
  ' StorageStereotypeFontSize
  ' StorageStereotypeFontStyle
  
  ' Style
  ' SvglinkTarget
  
  '
  ' Swimlane
  '
  SwimlaneBorderColor            $color_fg
  ' SwimlaneBorderThickness
  ' SwimlaneTitleBackgroundColor
  SwimlaneTitleFontColor    $color_font
  ' SwimlaneTitleFontName
  ' SwimlaneTitleFontSize
  ' SwimlaneTitleFontStyle
  ' SwimlaneWidth
  ' SwimlaneWrapTitleWidth

  ' TabSize

  '
  ' Timing
  '
  TimingFontColor   $color_font
  ' TimingFontName
  ' TimingFontSize
  ' TimingFontStyle

  '
  ' Title
  '
  ' TitleBackgroundColor
  ' TitleBorderColor
  ' TitleBorderRoundCorner
  ' TitleBorderThickness
  TitleFontColor    $color_font
  ' TitleFontName
  ' TitleFontSize
  ' TitleFontStyle

  '
  ' Usecase
  '
  UsecaseBackgroundColor       $color_bg_light
  UsecaseBorderColor           $color_primary
  ' UsecaseBorderThickness
  UsecaseFontColor    $color_font
  ' UsecaseFontName
  ' UsecaseFontSize
  ' UsecaseFontStyle
  UsecaseStereotypeFontColor    $color_font
  ' UsecaseStereotypeFontName
  ' UsecaseStereotypeFontSize
  ' UsecaseStereotypeFontStyle
  
  ' WrapWidth
}

@enduml